library(reticulate)

# Keep this script aligned with the notebook's requested Python environment.
Sys.unsetenv("RETICULATE_PYTHON")
use_condaenv("py311_arm", required = TRUE)

python <- py_config()$python
requirements <- system2(
  python,
  args = c("-m", "pip", "freeze"),
  stdout = TRUE
)

deployment_requirements <- c(
  "ipython>=8.0.0",
  "nbformat>=5.0.0",
  "networkx"
)

installed_packages <- tolower(sub("([<>=!~].*)$", "", requirements))
missing_deployment_requirements <- deployment_requirements[
  !tolower(sub("([<>=!~].*)$", "", deployment_requirements)) %in% installed_packages
]

writeLines(
  c(
    paste("# requirements.txt generated by scripts/requirements.R on", Sys.time()),
    requirements,
    missing_deployment_requirements
  ),
  "requirements.txt"
)
