library(reticulate)

# Keep this script aligned with the notebook's requested Python environment.
Sys.unsetenv("RETICULATE_PYTHON")
use_condaenv("py311_arm", required = TRUE)

python <- py_config()$python
requirements <- system2(
  python,
  args = c("-m", "pip", "freeze"),
  stdout = TRUE
)

writeLines(
  c(
    paste("# requirements.txt generated by scripts/requirements.R on", Sys.time()),
    requirements
  ),
  "requirements.txt"
)
